[package]
name = "timehistory-bash"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[dependencies]
bash-builtins = "0"
libc = "0"
memchr = "2.4.0"
once_cell = "1.8.0"
plthook = "0"

[lib]
crate-type = [ "cdylib" ]
